package bytewordreplacer;

import javax.swing.JDialog;
import javax.swing.JFileChooser;
import java.awt.BorderLayout;
import java.io.File;



/** Just JDialog with JFileChooser
 * @author MKedzie
 *
 */
public class FolderSelectWindow{
	/**
	 * 
	 */
	protected JDialog dialog;
	/**
	 * 
	 */
	protected File file;
	/**
	 * 
	 */
	private JFileChooser fileChooser;
	/**
	 * 
	 */
	public FolderSelectWindow() {
		common();
	}
	/** Autogenerated 
	 * @param startfile if there is viable path in JTextPane responsible for folder path it will be starting path for JFileChooser. In other case this will be home folder for current session.
	 */
	public FolderSelectWindow(File startfile) {
		common();
		if(startfile.exists()) { // check if startfile exist
			fileChooser.setCurrentDirectory(startfile);
		}
	}
	
	private void common() {
		
		dialog = new JDialog();
		dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
		dialog.setSize(400, 400);
		file = null;
		fileChooser = new JFileChooser() {
			/** Accept button
			 *
			 */
			@Override
			public void approveSelection()
			{
				file = this.getSelectedFile();
				System.out.print(file.toString());
				dialog.dispose();
			}
			/** Cancell button
			 *
			 */
			@Override
			public void cancelSelection() {
				System.out.print("Wyjscie");
				dialog.dispose();
			}
			};
			
			
		fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		dialog.getContentPane().add(fileChooser, BorderLayout.CENTER);
		dialog.setVisible(true);
	}
	

	
}